### ISSUE TITLE
SIK İSTİYORUM!

### ISSUE THREAD

**Issue by Andromeda606** [sh4dowb/sikcoin#1]
Lütfen bana sik'ini ver. 

Ödeme bilgisi
URI: sikcoin:SXJQfuxVPJXcEdiwFvQKFYT5imywFi46eX?amount=0.00010000&label=BANA%20COIN%20VER&message=BANA%20COIN%20VER
adres: SXJQfuxVPJXcEdiwFvQKFYT5imywFi46eX
Tutar: 0.00010000 SIK
etiket: BANA COIN VER
Mesaj: BANA COIN VER

**Comment by sh4dowb** [comment]
merhaba, 500 SİK yolladım. iyi günlerde harca!
txid: f785ea646b5493e93c6c43d325c2650255aa50a202a9f509e4346bb63230cfb1

**Comment by Andromeda606** [comment]
![image](https://user-images.githubusercontent.com/43077625/116006695-04346a00-a615-11eb-8a65-5a5bb7672000.png)
hocam burası neden çalışmıyor VE AYRICA SIKLER İÇİN TEŞEKKÜR EDERİM!

**Comment by sh4dowb** [comment]
> ![image](https://user-images.githubusercontent.com/43077625/116006695-04346a00-a615-11eb-8a65-5a5bb7672000.png)
> hocam burası neden çalışmıyor VE AYRICA SIKLER İÇİN TEŞEKKÜR EDERİM!

fanların dönmeye başladığını farketmişsinizdir, şuan sik kazıyorsunuz!
eğer konsoldan `[ ]` çıktısı gelirse bir daha `generate 1` yazıp bekleyin. sikcoin kazmak biraz uzun sürüyor tabi, 10 dakika içinde falan bulması lazım ama bir blok

edit: r10'dan da ban yemişiz yav.
Aşağıdaki sebep´ten dolayı yasaklandınız:
Edepsizlik ne vakit meşru komedi malzemesi oldu? - https://www.r10.net/maxigeyik/2792383-sikcoin-cikarttim-sanal-internet-koini.html
Yasaklandığınız süre: 02-05-2021, 22:00:00

saçmalık. sanal internet koini çıkarıp paylaşamayacak mıyız? ondan sonra neden gelişemiyoruz!

**Comment by Andromeda606** [comment]
Sanal internet koini her yerde kullanılacak! ödemelerimi bununla alacağım çünkü gas ücreti çok düşük! teşekkür ederim

**Comment by sh4dowb** [comment]
umarız bir gün herkes ödemeleri sik'iyle yapar. desteğiniz için teşekkürler!

**Comment by Andromeda606** [comment]
r10 da 500 SIK için 0.5 tl istesem ban yer miyim acaba.
