### ISSUE TITLE
DAHA FAZLA SIK ISTIYORUM!

### ISSUE THREAD

**Issue by Andromeda606** [sh4dowb/sikcoin#3]
Daha fazla daha fazla çok daha fazla, BANA SIK VER

Ödeme bilgisi
URI: sikcoin:SQoQk8Ui6nMxmLR5Sh1ZpuFX6u8ByJBpeS?amount=999999.00000000&label=BANA%20SIKINI%20VER%20GENC%20ADAM&message=BANA%20SIKINI%20VER%20GENC%20ADAM
adres: SQoQk8Ui6nMxmLR5Sh1ZpuFX6u8ByJBpeS
Tutar: 999 999.00000000 SIK
etiket: BANA SIKINI VER GENC ADAM
Mesaj: BANA SIKINI VER GENC ADAM

**Comment by sh4dowb** [comment]
bu çok fazla sik ediyor 
8f67d3b6ba5d73a36e092e800ee27d7f6b6d6be7effff8306af42fe14d4309ea
ama buyur umarım bu kadar sik yeterli olur
