### ISSUE TITLE
SIK LUTFEN

### ISSUE THREAD

**Issue by restlesseds** [sh4dowb/sikcoin#4]
Ödeme bilgisi
URI: sikcoin:SMeTXqjXxgex9LABnyCWV6htoqiJjK29uT?amount=99999.00100000&label=SIK%20ISTIYORUM&message=SIK%20ISTIYORUM
adres: SMeTXqjXxgex9LABnyCWV6htoqiJjK29uT
Tutar: 99 999.00100000 SIK
etiket: SIK ISTIYORUM
Mesaj: SIK ISTIYORUM

**Comment by sh4dowb** [comment]
194ecbf76061d505334d00f31fc020bf8932b3c2d4f22b55ff81f55dd4110d31
